import MainHeader from "@/components/MainHeader"
import { Toaster } from "@/components/Toaster"
import { Poppins } from "next/font/google"
import "./globals.css"

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["400", "500"],
})
export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={`min-h-screen bg-white  ${poppins.className}`}>
				<div className="mx-auto max-w-5xl">
					<MainHeader />
					{children}
				</div>
				<Toaster />
			</body>
		</html>
	)
}
